### PR TITLE
Add sig refresh

### PR DESCRIPTION
**Pull request by hillyu**
it would be useful to add custom signals for script refresh so the script can be triggered by signals instead of constantly polling/refreshing. This is useful for things like album cover update on music player's track/status changes. 
By the way, do you guys think using real-time signal would be better? i.e. ``RTMIN+No``.  Think those status bars mostly use that for triggering update.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Sorry for the late reply.

I'm working hard on integration of all the nwg-shell stuff in a real shell, for use with ArchLabs Linux. Wouldn't like to make changes before I'm adding the wrapper, which should happen soon. I'll get back to your PR as soon as I can.

**Comment by hillyu** [comment]
sure thing, no worries, I made a few more changes here. Including making the anchor for top/bottom  checking `align` and anchor to one at a time, instead of anchor to both top and bottom at the same time, old way would make aligning multiple `widget` a real pain. Take your time and really like this project, I made some really good looking yet practical dashboards with it :D  keep up the good work!
image

whatever I change will be updated here: https://github.com/hillyu/nwg-wrapper/tree/dev.

**Comment by nwg-piotr** [comment]
It looks very well. Would you mind contributing some of your work, e.g. to the `examples` folder?

**Comment by hillyu** [comment]
Will do. It's still a work in progress and I will certainly contribute once they are ready.

**Comment by nwg-piotr** [comment]
Funny thing: this is just a simple script, which I wrote in one evening, on request of some guy on reddit. Good thing it turns out useful to more people.

**Comment by hillyu** [comment]
#11 selected a few script I did as an example.

**Comment by nwg-piotr** [comment]
Thank you! I have a few days off starting from tomorrow. Will review/merge your work.

**Pull request merged**
